# Generated by Django 4.2.6 on 2023-11-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('DELETE', 'DELETE'), ('PUT', 'PUT')])),
                ('endpoint', models.CharField(default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
        migrations.DeleteModel(
            name='ServiceEndpoints',
        ),
        migrations.AddField(
            model_name='serviceendpoint',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.server'),
        ),
    ]
