# Generated by Django 4.2.6 on 2023-11-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_serviceendpoint_rename_urls_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceendpoint',
            name='method',
            field=models.CharField(choices=[('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT'), ('GET', 'GET')]),
        ),
    ]
