# Generated by Django 4.2.6 on 2023-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_serviceendpoint_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceendpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('DELETE', 'DELETE'), ('PUT', 'PUT'), ('POST', 'POST')], default='GET'),
        ),
    ]
