# Generated by Django 4.2.6 on 2023-11-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_serviceendpoint_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='urls',
            field=models.ManyToManyField(to='registry.url'),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='endpoint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT')], default='GET', max_length=10),
        ),
    ]
