# Generated by Django 4.2.6 on 2023-11-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_serviceendpoint_urls_alter_serviceendpoint_endpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceendpoint',
            name='urls',
        ),
    ]
