# Generated by Django 4.2.6 on 2023-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_remove_serviceendpoint_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='name',
            field=models.CharField(default='Undefined', max_length=255),
        ),
    ]
